import os
import time
import statistics
import torch
import numpy as np

from vae.qdVAE import QD 
from vae.VAEConfigs import Configs
from problem.IDPCNDU import IDPCNDU

def run(fw, tasks_info):
    """
    hàm chạy chính
    """
    print(f"Starting Multitask Execution for {len(tasks_info)} tasks concurrently...")
    
    # Dictionaries to store statistics for each task across all seeds
    bf = {i: float('inf') for i in range(len(tasks_info))}
    rs = {i: [] for i in range(len(tasks_info))}
    time_records = {i: [] for i in range(len(tasks_info))}
    
    for seed in range(Configs.REPEAT):
        Configs.rd.seed(seed)
        torch.manual_seed(seed)
        np.random.seed(seed)

        print(f"============ Running Seed {seed} ============")
        
        t1 = time.time()
        total_vae_training_time = 0.0
        
        workers = []
        log_files = []
        for i, (d_path, o_dir, name) in enumerate(tasks_info):  
            task = IDPCNDU()
            task.read_data(d_path)
            
            # Mỗi task là một instance QD, workers là list lưu các tasks.
            worker = QD(task, o_dir, name)
            workers.append(worker)
            
            # Setup generation logging
            gen_file = open(os.path.join(o_dir, f"{name}_seed({seed}).gen"), "w")
            gen_file.write(f"Generations {name}\n")
            log_files.append(gen_file)

        generation = 0
        transfer_interval = Configs.TRANSFER_INTERVAL_GEN

        # block chạy
        while generation < Configs.MAX_GENERATIONS:

            # Ở đây, mỗi worker sẽ chạy luồng thông thường sau 1 lượng Configs.TRANSFER_INTERVAL_GEN
            # sau đó mới thực hiện chuyển giao tri thức.
            for i, worker in enumerate(workers):
                worker.run_batch(generations=transfer_interval, fw_gen=log_files[i], global_gen_start=generation)
            generation += transfer_interval
            
            if generation >= Configs.MAX_GENERATIONS: 
                break

            print(f"\n[Gen {generation}] Triggering Cross-Task Knowledge Transfer...")
            
            # Block B: Trích xuất elite và train các VAEs cho mỗi tasks.
            vaes = []
            archives_mock = []
            for worker in workers:
                # THE FIX: Catch all 4 returned values from train_and_get_vae()
                try:
                    vae_model, elite_genotypes, train_time, loss_history = worker.train_and_get_vae()
                except ValueError:
                    print(f"Error extracting VAE for {worker.file_name}. Skipping...")
                    vae_model, elite_genotypes, train_time = None, [], 0.0
                
                total_vae_training_time += train_time
                vaes.append(vae_model)
                
                # Mock archive dictionary required by the KT logic
                mock = {idx: gen for idx, gen in enumerate(elite_genotypes)} if elite_genotypes else {}
                archives_mock.append(mock)

            # Block C (đã sửa): Perform Cross-Pollination (Task A gets Task B's VAE, etc.)
            for target_idx, target_worker in enumerate(workers):
                for source_idx, source_vae in enumerate(vaes):
                    # A task cannot transfer knowledge to itself; only accept from foreign tasks
                    if target_idx == source_idx or source_vae is None:
                        continue
                    
                    source_dim = workers[source_idx].task_dim
                    
                    # Target worker receives knowledge generated by the Source VAE
                    target_worker.kt.receive_knowledge(
                        target_worker=target_worker,
                        source_vae=source_vae,
                        source_dim=source_dim,
                        target_archive_mock=archives_mock[target_idx],
                        batch_size=Configs.TRANSFER_BATCH_SIZE
                    )

        t2 = time.time()
        adjusted_duration_sec = (t2 - t1) - (total_vae_training_time / len(tasks_info))
        
        for i, worker in enumerate(workers):
            log_files[i].close()
            
            # Get the absolute best solution from the MAP-Elites grid
            final_best_ind = max(worker.archive.values(), key=lambda ind: ind.fitness)
            
            # Trigger your custom .opt save mechanism inside the QD class
            worker.save(seed, final_best_ind.fitness, t1, t1 + adjusted_duration_sec)
            
            current_cost = -final_best_ind.fitness
            bf[i] = min(bf[i], current_cost)
            rs[i].append(current_cost)
            time_records[i].append(adjusted_duration_sec / 60.0)
            
            print(f"Task {i} ({tasks_info[i][2]}) Seed {seed} Best distance: {current_cost}")

    # Handle stats
    for i, (d_path, o_dir, name) in enumerate(tasks_info):
        avg_val = statistics.mean(rs[i])
        std_val = statistics.stdev(rs[i]) if len(rs[i]) > 1 else 0.0
        avg_time_per_run = statistics.mean(time_records[i])
        
        line = f"{name}\t{int(bf[i])}\t{avg_val:.2f}\t{std_val:.2f}\t{avg_time_per_run:.2f}\n"
        fw.write(line)
    fw.flush()

def build_model(fw, file_path, data_path):
    input_list_file = os.path.join(file_path, "file.txt")
    if not os.path.exists(input_list_file):
        print(f"Warning: {input_list_file} not found.")
        return

    tasks_info = []
    with open(input_list_file, 'r') as sc:
        header = sc.readline() # skip dòng đầu
        
        for line in sc:
            name = line.strip()
            if not name:
                continue
            
            out_dir = os.path.join(file_path, name)
            if not os.path.exists(out_dir):
                os.makedirs(out_dir)
            
            dt_path = os.path.join(data_path, name + ".txt")

            tasks_info.append((dt_path, out_dir, name))
            
        run(fw, tasks_info)
def main():
    print("Running VAE-Integrated Solver...")
    print("Is Torch available?", torch.cuda.is_available())
    if (not torch.cuda.is_available()):
        print("Config CUDA first!, exiting...")
        return 
    
    data_path = "D:\\multi-nde-py\\dataset" 
    output_path = "g_output"
    result_file = os.path.join("g_output", "test.txt")
    
    if not os.path.exists(output_path):
        os.makedirs(output_path)
    
    children = []
    if os.path.exists(output_path):
        for entry in os.scandir(output_path):
            if entry.is_dir():
                children.append(entry)

    def sort_key(entry):
        try:
            return entry.name.split("_")[1]
        except IndexError:
            return entry.name

    children.sort(key=sort_key, reverse=True)
    
    with open(result_file, "a") as fw:
        for entry in children:
            file_path = entry.path
            
            # Basic check to skip non-directory files
            if not entry.is_dir():
                continue
            
            print(f"Processing directory: {entry.name}")
            build_model(fw, file_path, data_path)
            
    print("DONE!")

if __name__ == "__main__":
    main()